SCA.Indigo.Web.UI/Controllers/MassDataImportController.cs
// ***********************************************************************
// Assembly         : SCA.Indigo.Web.UI
// Author           : Sachin
// Created          : 12-Jun-2015
//
// Last Modified By : 
// Last Modified On : 
// ***********************************************************************
// <copyright file="MassDataImportController.cs" company="Capgemini">
//     Capgemini. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace SCA.Indigo.Web.UI.Controllers
{
    using System;
    using System.Globalization;
    using System.Web.Mvc;
    using SCA.Indigo.Web.UI.Helper;
    using SCA.Indigo.Web.UI.ViewModel.MassChanges;
    using SCAEnums = SCA.Indigo.Common.Enums.SCAEnums;
    using LinqToExcel;
    using System.Collections.Generic;
    using System.Web;
    using System.IO;
    using SCA.Indigo.Common;

    /// <summary>
    /// Mass Data Import Controller
    /// </summary>
    [Authorize]
    public class MassDataImportController : Controller
    {
        /// <summary>
        /// mass Data Import Helper
        /// </summary>
        MassDataImportHelper massDataImportHelper = new MassDataImportHelper();

        /// <summary>
        /// The user identifier
        /// </summary>
        private string userId = ControllerHelper.CurrentUser.UserId.ToString();

        // GET: MassDataImport
        public ActionResult Index()
        {
            return View();
        }

        #region MasterMassDataImport

        /// <summary>
        /// Uploads the File.d
        /// </summary>
        /// <param name="attachmentViewModel">The attachment view model.</param>e
        /// <returns>
        /// return status of uploaded File
        /// </returns>
        [HttpPost]
        public ActionResult ImportData(HttpPostedFileBase uploadedFile, int selectedTemplate, bool isImport)
        {
            var objMassDataImportHelper = new MassDataImportHelper();
            var objMasterMassDataImportViewModel = new MasterMassDataImportViewModel();
            objMasterMassDataImportViewModel.UploadedFile = uploadedFile;
            objMasterMassDataImportViewModel.SelectedTemplate = selectedTemplate;
            objMasterMassDataImportViewModel.IsImport = isImport;
            objMasterMassDataImportViewModel = objMassDataImportHelper.ImportData(objMasterMassDataImportViewModel);

            LogHelper.LogAction(Constants.ActionMethodImportData, Constants.MassDataImportController, Constants.ActionMethodImportData, this.userId);

            return this.Json(new
            {
                Status = objMasterMassDataImportViewModel.Status,
                Message = objMasterMassDataImportViewModel.Message,
                LogFilePath = objMasterMassDataImportViewModel.LogFilePath,
                validationRows = objMasterMassDataImportViewModel.TemplateValidationRows
            }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Get Mass Data Import Details
        /// </summary>
        /// <returns>action result</returns>
        public ActionResult GetMassDataImportDetails()
        {
            MasterMassDataImportViewModel masterMassDataImportViewModel = new MasterMassDataImportViewModel();
            var importTempletListId = Convert.ToInt64(SCAEnums.ListType.MassDataTemplate, CultureInfo.InvariantCulture);
            long languageId = Convert.ToInt64(SCAEnums.ListType.LanguageId, CultureInfo.InvariantCulture);

            var listIds = new[] { importTempletListId };
            masterMassDataImportViewModel = this.massDataImportHelper.GetImportTemplateDropDown(listIds, languageId);

            LogHelper.LogAction(Constants.ActionMethodGetMassDataImportDetails, Constants.MassDataImportController, Constants.ActionMethodGetMassDataImportDetails, this.userId);
            return View(Constants.ActionMassDataImport, masterMassDataImportViewModel);
        }

        #region Dowmload Template
        /// <summary>
        /// Download Mass Data Template
        /// </summary>
        /// <param name="selectedTemplateValue"></param>
        /// <returns>action result</returns>
        [HttpPost]
        public ActionResult DownloadMassDataTemplate(int selectedTemplateValue)
        {
            string templateFilePath = string.Empty;
            templateFilePath = massDataImportHelper.GetTemplateFilePath(selectedTemplateValue, true);
            LogHelper.LogAction(Constants.ActionMethodDownloadMassDataTemplate, Constants.MassDataImportController, Constants.ActionMethodDownloadMassDataTemplate, this.userId);
            return Json(templateFilePath, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #endregion
    }
}

SCA.Indigo.Web.UI/Views/MassDataImport/MassDataImport.cshtml
@model SCA.Indigo.Web.UI.ViewModel.MassChanges.MasterMassDataImportViewModel
@using SCA.Indigo.Web.UI.Resource
@using System.Configuration;
@using SCA.Indigo.Web.UI.Helper
@using SCA.Indigo.Common.Enums

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <script type="text/javascript">
    </script>
    <style>
        .form_main_btns {
            padding: 10px 0px;
        }

        .search_cell {
            padding: 6px 10px;
        }

        .page_heading {
            padding-top: 5px;
        }

        .padding_left_173 {
            padding-left: 173px;
        }

         .j_lightbox_error .j_lightbox_error_wrapper { width:32%; left:32%;}
        .pop_error {text-align:center;}
    </style>

</head>
<body>
    <script type="text/javascript">
        $jqGrid = jQuery.noConflict();
        $jqGrid(document).ready(function () {
            $jqGrid("#jqInvalidTemplateColumn").jqGrid({
                datatype: "local",
                colNames: ['TemplateColumn', 'UploadedColumn'],
                colModel: [
                    { name: 'TemplateColumnName', index: 'TemplateColumnName', editable: false, width: '200px'},
                    { name: 'UploadColumnName', index: 'UploadColumnName', editable: false, width: '200px'}
                ],
                height: '130',
                autowidth: false,
                toppager: false,
                ignoreCase: true,
                jsonReader: { repeatitems: false },                
                rowNum: 50,
                rowList: [50, 100, 150, 200, 250, 300, 350, 400, 450, 500],
                viewrecords: true,                
                sortname: "",
                sortorder: "asc",
                loadComplete: function (data) {
                }
            })
        });
    </script>

    <form id="frm_MasterMassDataImport">
        
        <span class="page_heading">@Common.resMassDataImportHeader</span>
        <div class="report_builder_select_fields margin_top_0 margin_bot_0">
            <span class="heading-1 span_expnd width_100p">Download Template for Mass Data Import</span>
            <div class="padding_top_bot_20 border_all collapse">
                <ul class="report_builder_criteria_ul  margin_left_25 margin_top_0">
                    <li>
                        <div class="report_builder_criteria_cell_2">
                            <span class="input_lable width_130">@Common.resLabelDownloadType</span>
                            <span class="report_builder_cust_name_select_2 select-style width_260">
                                @Html.DropDownList("ddlImportDropdown", Model.ImportTemplate, @Common.resTemplateDropdown, new { @class = "custom-select" })
                            </span>
                        </div>
                    </li>
                </ul>
                @*<div class="map_rols_user_cell new_select_for_search margin_bot_12 margin_left_25">
                <span class="patientinfo_col2_lable font_12bold width_164">@Common.resLabelDownloadTemplate</span>
                <span class="map_rols_user_input select-style">
                    @Html.DropDownList("ddlImportDropdown", Model.ImportTemplate, @Common.resTemplateDropdown, new { @class = "custom-select" })
                </span>
            </div>*@
                <div class="padding_left_142 clear" id="divDownloadData">
                    <a href="javascript:void(0);" class="form_buttons padding_left_right_15 margin_left_25 small_btn" id="DownloadButton">@Common.resLabelDownloadTemplate</a>&nbsp;&nbsp;
                </div>
            </div>

            <div class="clear"></div>
            <div style="height:20px;">&nbsp;</div>
        </div>
        <div class="report_builder_select_criteria margin_top_15">
            <span class="heading-1 prescription-information-icon width_100p span_expnd">Upload Data for Mass Data Import</span>
            <div class="padding_top_bot_20 border_all collapse">
                <ul class="report_builder_criteria_ul  margin_left_25 margin_top_0 margin_bot_0">
                    <li>
                        <div class="report_builder_criteria_cell_2">
                            <span class="input_lable width_130">@Common.resLabelUploadType</span>
                            <span class="report_builder_cust_name_select_2 select-style width_260">
                                @Html.DropDownList("ddlUploadDropdown", Model.ImportTemplate, @Common.resddlUploadTypeDefaultValue, new { @class = "custom-select" })
                            </span>
                        </div>
                    </li>
                </ul>
               
                <div id="divUploadFile" class="margin_left_25">

                    <div id="UploadExcelFileUploadControl">
                        <input type="file" name="UploadExcelFileControl" id="UploadExcelFileControl" onchange="UploadExcelObj.FileUploadChange(this)" disabled="disabled" />
                    </div>
                    
                    <input type="hidden" value="@System.Configuration.ConfigurationManager.AppSettings["MaxAttachSizeInMB"].ToString()" id="hdnAppConfigMaxSixe" />
                    <input type="hidden" value="@Common.resFileSize" id="hdnFilzSize">
                    @Html.Hidden("hdnDownLoadTemplateUrl", Url.Action("DownloadMassDataTemplate", "MassDataImport"), new { id = "hdnDownLoadTemplateUrl" })

                    <div class="j_lightbox_error" id="j_lightbox_error">
                        <div class="j_lightbox_error_wrapper">
                            <div class="pop_error">
                                <div id="divUploadExcelErrorMessage" class="pop_error">
                                </div>
                                <br />
                                <div class="j_lightbox_btns search_form_main_btns">
                                    <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15 j_lightbox_error_ok">@Common.resbtnErrorOk</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="form_main_btns margin_left_25">
                    @*<a href="javascript:void(0);" id="resbtnSave" class="search_form_buttons padding_left_right_20" onclick="MassDataImportObj.ReadExcelData();">@Common.resbtnSave</a>&nbsp;*@
                    <a href="javascript:void(0);" class="search_form_buttons padding_left_right_20" id="btnUpload" onclick="MassDataImportObj.ImportData()">@Common.resbtnFileUpload</a>&nbsp;
                    <a href="javascript:void(0);" id="btnMassChangesUndo" class="search_form_buttons padding_left_right_20">@Common.resBtnGeneralReset</a>
                </div>
            </div>
        </div>
        <div class="j_lightbox_error" id="j_lightbox_error">
            <div class="j_lightbox_error_wrapper">
                <div class="pop_error">
                    <div id="divErrorMessage" class="pop_error">
                    </div>
                    <br />
                    <div class="j_lightbox_btns search_form_main_btns">
                        <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15 j_lightbox_error_ok">@Common.resbtnErrorOk</a>
                    </div>
                </div>
            </div>
        </div>

        <div style="display: none">
            <input type="hidden" id="hdnMassDataImportController" value="@Constants.MassDataImportController" />
            <input type="hidden" id="hdnEnumOrder" value="@Convert.ToInt32(SCAEnums.MassDataTemplate.Order)" />
            <input type="hidden" value="@Common.resInvalidExcelFormat" id="hdnExcelFormat">            
            <input type="hidden" id="hdnFilNotSelected" value="@Common.resFilNotSelected" />           
        </div>
        @Scripts.Render("~/bundles/MassDataImport")

        <div class="j_lightbox_error" id="divAlertErrorToview">
            <div class="j_lightbox_error_wrapper contactInfo">
                <div class="pop_error">
                    <div id="validationText"></div>
                    <br/>
                    <div id="validationErrorjqWrapper">
                        @Common.rellblInvalidTemplateColumn
                     <table id="jqInvalidTemplateColumn"></table>   </div>                 
                    <br/>                                      
                    <input type="button" id="btnCloseValidationPopup" onclick="closeValidationPopup()" value="OK" class="search_form_buttons padding_left_right_20">
                    
                </div>
            </div>
        </div>


        <div id="divCancelPrompt" style="display:none" class="validation_msg">
            @*<label class="validation_msg">@Common.resMessageUnsavedChanges</label>
                <br />*@
            <label class="validation_msg">@Common.resGeneralUndoMessage</label>
        </div>
        <div class="j_lightbox_error" id="j_lightbox_error">
            <div class="j_lightbox_error_wrapper">
                <div class="pop_error">
                    <div id="divMasssChangeErrorMessage" class="pop_error">
                    </div>
                    <br />
                    <div class="j_lightbox_btns search_form_main_btns">
                        <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15 j_lightbox_error_ok">@Common.resbtnErrorOk</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>

</html>