SCA.Indigo.Web.UI/Controllers/PatientController.cs
// ***********************************************************************
// Assembly         : SCA.Indigo.Web.UI
// Author           : syerva
// Created          : 12-03-2014
//
// Last Modified By : syerva
// Last Modified On : 01-08-2015
// ***********************************************************************
// <copyright file="PatientController.cs" company="Capgemini">
//     Capgemini. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace SCA.Indigo.Web.UI.Controllers
{
	using System;
	using System.Collections.Generic;
	using System.Globalization;
	using System.Linq;
	using System.Web.Mvc;

	using SCA.Indigo.Business.BusinessModels;
	using SCA.Indigo.Common;
	using SCA.Indigo.Common.Enums;
	using SCA.Indigo.Web.UI.Helper;
	using SCA.Indigo.Web.UI.ViewModel;
	using SCA.Indigo.Model;
	using System.Configuration;

	/// <summary>
	/// Class PatientController.
	/// </summary>
	[Authorize]
	public class PatientController : Controller
	{
		// Global varriable        
		/// <summary>
		/// The _user password expired
		/// </summary>
		private readonly bool userPasswordExpired = Convert.ToBoolean(ControllerHelper.CurrentUser.IsExpired, CultureInfo.InvariantCulture);
		/// <summary>
		/// The _obj patient view model
		/// </summary>
		private readonly SearchViewModel globalObjPatientViewModel = new SearchViewModel();
		/// <summary>
		/// The _obj selectedvalue
		/// </summary>
		private readonly SelectedValue globalObjSelectedvalue = new SelectedValue();
		/// <summary>
		/// The _obj patient information view model
		/// </summary>
		private PatientInfoViewModel globalObjPatientInfoViewModel = new PatientInfoViewModel();
		/// <summary>
		/// The user identifier
		/// </summary>
		private string globalUserId = Convert.ToString(ControllerHelper.CurrentUser.UserId, CultureInfo.CurrentCulture);
		/// <summary>
		/// The _user login name
		/// </summary>
		private readonly string userLoginName = Convert.ToString(ControllerHelper.CurrentUser.UserName, CultureInfo.CurrentCulture);
		/// <summary>
		/// The _user type
		/// </summary>
		private readonly string userType = Convert.ToString(ControllerHelper.CurrentUser.UserType, CultureInfo.CurrentCulture);
		/// <summary>
		/// The _ role name
		/// </summary>
		private readonly string roleName = Convert.ToString(ControllerHelper.CurrentUser.RoleName, CultureInfo.CurrentCulture);
		/// <summary>
		/// The _ role identifier
		/// </summary>
		private readonly long roleId = Convert.ToInt64(ControllerHelper.CurrentUser.RoleId, CultureInfo.CurrentCulture);
		/// <summary>
		/// The date format
		/// </summary>
		private const string DateFormat = "dd/MM/yyyy";

		private bool IsClinicalContactWithLinkage
		{
			get
			{
				if (Session[Constants.SessionCustomerParameters] != null)
				{
					var customerParameterValue = (List<CustomerParameterBusinessModel>)Session[Constants.SessionCustomerParameters];
					return customerParameterValue.FirstOrDefault().IsClinicalContactWithLinkage;
				}
				return false; //This will be only if the session is expired. In ideal scenario, this will be never executed. But included the code to avoid any runtime exception.
			}
		}


		/// <summary>
		/// The customer helper
		/// </summary>
		CustomerHelper customerHelper = new CustomerHelper();
		/// <summary>
		/// The patient helper
		/// </summary>
		PatientHelper patientHelper = new PatientHelper();

		/// <summary>
		/// Get function for Patient Info
		/// </summary>
		/// <returns>
		/// Action Result
		/// </returns>
		public ActionResult PatientInfo()
		{
			return View(Constants.ViewPatientInfo);
		}

		/// <summary>
		/// Loads the drop downs.
		/// </summary>
		/// <returns></returns>
		[HttpGet]
		public ActionResult LoadDropDowns()
		{
			var guidKey = Guid.NewGuid();
			FillDropDownData(globalObjSelectedvalue);
			globalObjPatientInfoViewModel.UserType = ControllerHelper.CurrentUser.UserType.ToString(CultureInfo.InvariantCulture);
			return Json(globalObjPatientInfoViewModel, JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// This method will load patient information based on provided PatientId
		/// </summary>
		/// <param name="patientId">Patient Id to load the patient details</param>
		/// <param name="customerId">Customer id of the patient</param>
		/// <param name="PatientName">Name of the patient</param>
		/// <param name="CustomerName">Customer name of the patient</param>
		/// <param name="SAPCustomerNumber">Sap Customer Number</param>
		/// <param name="SAPPatientNumber">Sap Patient Number</param>
		/// <returns>
		/// Full details of the Patient along with patient's Medical staff and Prescription
		/// </returns>
		public ActionResult LoadPatientDetails(string patientId, string customerId, string PatientName, string CustomerName, string SAPCustomerNumber, string SAPPatientNumber)
		{
			var guidKey = Guid.NewGuid();

			Session[Constants.SessionIsLoadPrescription] = true;
			Session[Constants.SessionPatientId] = patientId;
			Session[Constants.SessionCustomerId] = customerId;
			Session[Constants.SessionPreviousCustomerId] = customerId;
			globalObjPatientViewModel.ViewModelPatientInfo = new PatientInfoViewModel();
			globalObjPatientInfoViewModel.PatientId = !string.IsNullOrEmpty(patientId) ? Convert.ToInt64(patientId, CultureInfo.InvariantCulture) : 0;

			FillPatientDetails();

			FillDropDownData(globalObjSelectedvalue);

			globalObjPatientViewModel.ViewModelPatientInfo = InitializePatientInfoViewModel(globalObjPatientInfoViewModel);
			Session[Constants.SessionPatientStatus] = globalObjSelectedvalue.PatientStatusSelectedValue;
			Session[Constants.SessionCopyPatientStatus] = globalObjSelectedvalue.PatientStatusSelectedValue;

			// Load PatientTypeMatrix
			var patientType = globalObjSelectedvalue.PatientTypeSelectedValue;
			LoadPatientTypeMatrix(Convert.ToInt64(globalObjPatientViewModel.ViewModelPatientInfo.CustomerId, CultureInfo.InvariantCulture), Convert.ToInt64(patientType, CultureInfo.InvariantCulture));

			if (Session[Constants.SessionisRedirectFromAuthorisation] != null && Convert.ToInt32(Session[Constants.SessionisRedirectFromAuthorisation], CultureInfo.InvariantCulture) == 1)
			{
				var patientDisplayName = patientId + " " + PatientName;
				var customerDisplayName = customerId + " " + CustomerName;
				SAPCustomerNumber = CommonHelper.TrimLeadingZeros(SAPCustomerNumber);
				customerDisplayName = !string.IsNullOrEmpty(SAPCustomerNumber) ? customerDisplayName.Contains(SAPCustomerNumber) ? customerDisplayName : customerDisplayName + "(" + SAPCustomerNumber + ")" : customerDisplayName;

				if (!string.IsNullOrEmpty(SAPPatientNumber))
				{
					patientDisplayName += " (" + SAPPatientNumber + ")";
				}

				Session[Constants.SessionpatientDisplayName] = Convert.ToString(patientDisplayName, CultureInfo.InvariantCulture);
				Session[Constants.SessionCustomerDisplayName] = Convert.ToString(customerDisplayName, CultureInfo.InvariantCulture);
			}
			if (Session[Constants.SessionCareHomeId] != null)
			{
				SetIsCarehomePatientProperty(globalObjPatientInfoViewModel);
			}
			return Json(globalObjPatientInfoViewModel, JsonRequestBehavior.AllowGet);
		}

		/// <summary>
		/// Initializes the patient information view model.
		/// </summary>
		/// <param name="inforViewModel">The infor view model.</param>
		/// <returns></returns>
		protected PatientInfoViewModel InitializePatientInfoViewModel(PatientInfoViewModel inforViewModel)
		{
			if (inforViewModel == null)
			{
				inforViewModel.SAPPatientNumber = string.IsNullOrEmpty(inforViewModel.SAPPatientNumber) ? string.Empty : inforViewModel.SAPPatientNumber;
				inforViewModel.CreatedBy = string.Empty;
				inforViewModel.CreatedDate = DateTime.Today.ToString(Constants.DateFormat, CultureInfo.InvariantCulture);
			}

			return inforViewModel;
		}

		/// <summary>
		/// This method will Add patient information based
		/// </summary>
		/// <param name="patientViewModel">The patient view model.</param>
		/// <returns>
		/// Action Result
		/// </returns>
		[HttpPost]
		public ActionResult AddDetails(PatientInfoViewModel patientViewModel)
		{
			globalObjPatientViewModel.ViewModelPatientInfo = globalObjPatientInfoViewModel;
			globalObjPatientViewModel.ViewModelPatientInfo.UserType = ControllerHelper.CurrentUser.UserType.ToString(CultureInfo.InvariantCulture);
			if (Session[Constants.SessionCareHomeId] != null)
			{
				SetIsCarehomePatientProperty(globalObjPatientViewModel.ViewModelPatientInfo);
			}
			return View(Constants.ActionSearch, globalObjPatientViewModel);
		}

		/// <summary>
		/// Gets the care home by identifier.
		/// </summary>
		/// <param name="careHomeId">The care home identifier.</param>
		/// <returns></returns>

		[HttpGet]
		public ActionResult GetCareHomeById(string careHomeId)
		{
			if (!string.IsNullOrEmpty(careHomeId))
			{
				CareHomeViewModel objCareHomeViewModel = new CareHomeHelper().GetCareHome(careHomeId);
				globalObjPatientInfoViewModel.CareHomeId = Convert.ToInt64(careHomeId, CultureInfo.InvariantCulture);
				globalObjPatientInfoViewModel.CustomerId = objCareHomeViewModel.CustomerId;
				globalObjPatientInfoViewModel.Address1 = objCareHomeViewModel.Address1;
				globalObjPatientInfoViewModel.Address2 = objCareHomeViewModel.Address2;
				globalObjPatientInfoViewModel.CareHomeName = objCareHomeViewModel.CareHomeName;
				globalObjPatientInfoViewModel.Country = objCareHomeViewModel.Country;
				globalObjPatientInfoViewModel.County = objCareHomeViewModel.County;
				globalObjPatientInfoViewModel.EmailAddress = objCareHomeViewModel.EmailAddress;
				globalObjPatientInfoViewModel.HouseName = objCareHomeViewModel.CareHomeName;

SCA.Indigo.Web.UI/Views/Patient/CopyDetails.cshtml
@using SCA.Indigo.Web.UI.Resource;
@using SCA.Indigo.Web.UI.Helper;
@model SCA.Indigo.Web.UI.ViewModel.PatientViewModel
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@Common.reslblTitle</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link href="~/Content/jquery.multiselect.css" rel="stylesheet" />
    <script type="text/javascript">

        $(document).ready(function () {

            $("#PatientId").text(@Session[Constants.SessionPatientId]);
            
            window.IsremovedVar = 1;
            HideApprovalDiv();


            var isFromAuthorisation = "@Convert.ToString(Session[Constants.SessionisRedirectFromAuthorisation])";
            var isFromOneOff = "@Convert.ToString(Session[Constants.SessionOrderSavedFromOneOff]).ToString().ToUpper()";
            var isFromOrderPage = "";

            $jqGrid.ajax({
                url: '/Patient/GetRedirectPage',
                async: false,
                cache: false,
                success: function (data) {
                    isFromOrderPage = data;
                    window.redirectPage = data;
                }
            });
        
            var PatientId = $('#hdnPatientId').val();
            var CustomerId = $('#hdnCustomerId').val();
            var PatientName = $('#hdnPatientName').val();
            var CustomerName = $('#hdnCustomerName').val();
            var SAPPatientNumber = $('#hdnSAPPatientNumber').val();
            var SAPCustomerNumber = $('#hdnSAPCustomerNumber').val();            
            isCopyDetails=true;

            window.patientId = PatientId;
            window.customerId = CustomerId;
            window.patientName = PatientName;
            window.customerName = CustomerName;
            window.SAPCustomerNumber = SAPPatientNumber;
            window.SAPPatientNumber = SAPCustomerNumber;

            $jqComm("ul.dock").addClass("free").animate({ left: "-1115px" }, 800);
            $jqComm("a.dock").css("display", "inline");
            $jqComm("a.undock").css("display", "none");

            $jqGrid('#btnEdit').removeClass("btn_disable");
            $jqGrid('#btnDownEdit').removeClass("btn_disable");
            $jqGrid('#btnRecentOrder').addClass("btn_disable")
            $jqGrid('#btnSampleOrder').addClass("btn_disable")
            $jqGrid('#btnInteractionsummary').addClass("btn_disable")
            $jqGrid('#btnPatientAuditLog').addClass("btn_disable")
            $jqGrid('#btnAttachment').addClass("btn_disable")
            $jqGrid('#btnContactInfo').addClass("btn_disable")
            $jqGrid('#btnNotes').addClass("btn_disable")
            if ($("#hdnAnyActiveOrder").val() == "false") { // If Patient has active order and Patient status Active
                if ($("#hdnCopyPatientStatus").val() == "10020") {
                    if (window.patientId > 0 && window.customerId != "" && window.patientName != "" && window.customerName != "") {
                        LoadCopyPatientDetails(PatientId, CustomerId, PatientName, CustomerName, SAPCustomerNumber, SAPPatientNumber);
                        $jqGrid("#JqPatientContactInfo").jqGrid('setGridParam', { postData: { patientId: PatientId, careHomeId: "", customerId: "" }, datatype: 'json' }).trigger('reloadGrid');
                    }
                    else {
                        $jqGrid('#divCopyPatientError').show();
                    }
                }
                else {
                    $jqGrid('#divCopyPatientStatusError').show();
                }
            }
            else {
                $jqGrid('#divCopyPatientActiveOrderError').show();
            }
            ShowCustomerPatientName();            
        });
        

        function LoadCopyPatientDetails(PatientId, CustomerId, PatientName, CustomerName, SAPCustomerNumber, SAPPatientNumber) {            
            $jqGrid.ajax({
                url: '@Url.Action("LoadPatientDetails","Patient")',
                type: 'POST',
                cache: false,
                async: false,
                data: { patientId: PatientId, customerId: CustomerId, PatientName: PatientName, CustomerName: CustomerName, SAPCustomerNumber: SAPCustomerNumber, SAPPatientNumber: SAPPatientNumber },
                success: function (data) {
                  
                    SetPatientDetails(data);
                                                          
                    window.CustomerParamets = data.CustomerParameters;                    
                    
                    $jqGrid("#jqPatientPrescription").jqGrid('setGridParam', { datatype: 'json' }).trigger('reloadGrid');                    
                    
                    DisableSaveButton();
                    EnableEditButton();
                    DisablePrescriptionButtons();
                    DisableCancelButton();                    
                    $jqGrid('#hdnOrderPage').val('');                    
                }
            });            
        }
    </script>
    <script type="text/javascript">
        $jqComm(window).load(function (e) {
            $jqComm("#gview_jqPatientAnalysis .ui-jqgrid-bdiv").mCustomScrollbar("destroy");
            $jqComm("#gview_jqMedicalStaffAnalysis .ui-jqgrid-bdiv").mCustomScrollbar("destroy");
            $(".staff_select_mode.staff_select_mode_collapse.collapse").toggle();
            $(".analysis_information.analysis_information_collapse.collapse").toggle();
        });
    </script>


</head>
<body>
    <div id="hdn">
        <input type="hidden" id="hdnIsredirectFromApproval" value=@Session[Constants.SessionisRedirectFromAuthorisation] title=@Session[Constants.SessionisRedirectFromAuthorisation] />        
        <input type="hidden" id="hdnPatientId" value="@Session[Constants.SessionPatientId]" />
        <input type="hidden" id="hdnCustomerId" value="@Session[Constants.SessionCustomerId]" />
        <input type="hidden" id="hdnPatientName" value="@Session[Constants.SessionPatientName]" />
        <input type="hidden" id="hdnCustomerName" value="@Session[Constants.SessionCustomerName]" />
        <input type="hidden" id="hdnSAPCustomerNumber" value="@Session[Constants.SessionSAPCustomerNumber]" />
        <input type="hidden" id="hdnSAPPatientNumber" value="@Session[Constants.SessionSAPPatientNumber]" />
        <input type="hidden" id="hdnAnyActiveOrder" value="@Session[Constants.SessionIsCopyActiveOrder]" />
        <input type="hidden" id="hdnCopyPatientStatus" value="@Session[Constants.SessionCopyPatientStatus]" />
        <input type="hidden" id="hdnCopyPatientId" value="@Session[Constants.SessionCopyPatientId]" />
        <input type="hidden" id="hdnCopyPreviousPatientID" value="" />            
    </div>

    <div>
        @*@section DetailPage{}*@
        <form id="PatientDetails">
            <div class="search_form_main_btns search_form_main_btns_1" id="divPatientMenuDetails">
                <div class="cust_pat_details width_605px" style="display:none">
                    <label title="Customer ID Customer Name (SAP ID)" id="lblCustomerName">Customer ID/Aron Watson/SAP ID</label>
                    <br />
                    <label title="Patient ID/Name" id="lblPatientName">Patient ID/Name</label>
                </div>
                <input type="button" value="@Common.resbtnSave" class="search_form_buttons padding_left_right_15 ClassSavePatient" id="btnDetailSave" onclick="SavePatientDetails(this.id)">
                <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15 BtnEditEnable" id="btnDetailsEdit">@Common.reslnkEdit</a>
                <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15 BtnExitSearch" id="btnDetailsExit">@Common.resBtnGeneralUndo</a>
                <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15" id="btnBackButton">@Common.resBack</a>
            </div>

            <div class="patientinfo_main">
                <span class="heading-1 patient-information-icon span_expnd"><i class="fa fa-file-text-o"></i> @Common.resPatientInformationTitle</span>
                <div id="DivPatientDetails" class="patient_information collapse">
                    @{Html.RenderPartial("_PatientInfo", Model.ViewModelPatientInfo);}
                </div>
                @{Html.RenderPartial("_PatientAnalysisMedicalStaff", Model.ViewModelPatientAnalysisMedicalStaff);}
                <span class="heading-1 prescription-information-icon span_expnd"><i class="fa fa-file-o"></i> @Common.resheadingPrescriptionInformation</span>
                <div class="prescription_nformation collapse">
                    <div class="prescription_dis_msg disable_msg">@Common.resMessageNoAccess</div>
                    @{Html.RenderPartial("_PatientPrescription", Model.ViewModelPatientPrescription);}
                </div>
                @if (Session[Constants.SessionisRedirectFromAuthorisation] != null || @Session[Constants.SessionisRedirectFromAuthorisation] != string.Empty)
                {
                    <div class="form_main_btns approver_section" id="divPrescriptionApprovalbtn">
                        <textarea class="note_textarea" placeholder="Add Note..." id="txtPrescriptionNote"></textarea><br /><br />
                        <input type="password" class="bg_eee Numeric NoCopyPaste" placeholder='@Common.resPlaceholderPIN' id="txtPIN">&nbsp;&nbsp;
                        <a href="javascript:void(0);" class="search_form_buttons padding_left_right_20" id="btnApprove">@Common.resbtnApprove</a>&nbsp;&nbsp;
                        <div id="divApprovalDialog" style="display:none" class="success_msg"></div>
                    </div>
                }

                <div class="j_lightbox_error" id="divAlertErrorToview">
                    <div class="j_lightbox_error_wrapper contactInfo">
                        <div class="pop_error">
                            <div id="divCopyDetailsErrorMessage">
                            </div>
                        </div>
                    </div>
                </div>
                <input type="hidden" id="hdnActionNameApprovePrescription" value="@Constants.ActionApprovePrescription" />
                <input type="hidden" id="hdnAuthorizeControllername" value="@Constants.AuthorizeController" />
                <input type="hidden" id="hdnmsgWrongPIN" value="@Common.resWrongPIN" />
                <input type="hidden" id="hdnmsgEnterPIN" value="@Common.resEnterPIN" />
                <input type="hidden" id="hdnmsgPrescriptionNotApproved" value="@Common.resErrorMsgprescriptionNotApproved" />
                <input type="hidden" id="hdnmsgPrescriptionApproved" value="@Common.resProductsApproved" class="success_msg" />
                <input type="hidden" id="hdnActionNameGetPIN" value="@Constants.ActionValidateUserAuthorizationPin" />
                <input type="hidden" id="hdnEnterPINPlaceholder" value="@Common.resPlaceholderPIN" />
                <input type="hidden" id="hdnActionClearCache" value="@Constants.ActionClearPrescriptionApprovalCache" />
                <input type="hidden" id="hdnPatientController" value="@Constants.PatientController" />
                <input type="hidden" id="hdnCustomerNameSave" value="@Session[Constants.SessionCustomerName]" />
                <input type="hidden" id="hdnOrderSavedFromOneOff" value='@Session[Constants.SessionOrderSavedFromOneOff]' />
                <input type="hidden" id="hdnRedirectFrom" value='@Session[Constants.SessionRedirectFrom]' />
                <input type="hidden" id="hdnPatientInteractionPatientName" value="@Session[Constants.SessionPatientName]" />
                <input type="hidden" id="hdnPatientInteractionCustomerName" value="@Session[Constants.SessionCustomerName]" />
                <input type="hidden" id="hdnPatientInteractionSAPCustomerNumber" value="@Session[Constants.SessionSAPCustomerNumber]" />
                <input type="hidden" id="hdnPatientInteractionSAPPatientNumber" value="@Session[Constants.SessionSAPPatientNumber]" />
                <input type="hidden" id="hdnPatientInteractionPatientId" value=@Session[Constants.SessionPatientId] />
                <input type="hidden" id="hdnPatientInteractionCustomerId" value=@Session[Constants.SessionCustomerId] />
                <input type="hidden" id="hdnSessionIsCalledFromCareHome" value="@Model.SessionIsCalledFromCareHome" />
                <span id="prescriptionMessage" class="field-validation-error text_align_left width_100p"></span>
                <input type="hidden" id="hdnOrderPage" value="@Common.resPageNameOrder" />
                <input type="hidden" id="hdnisRedirectFromProductOrder" value=@Session[Constants.SessionIsRedirectFromProductOrder] />
                <input type="hidden" id="hdnRedirectToViewPatient" value="@Url.Action("ViewDetails","Patient")" />
            </div>
            <section class="scrollup"><a href="javascript:void(0);">@Common.reslnkPageUp</a></section>
        </form>

    </div>
    <input type="hidden" id="hdnDetailsPage" value="Add Patient Details" />
    @Scripts.Render("~/bundles/CopyPatientDetails")
    <script src="~/Scripts/js/validations/Order.js"></script>
    <input type="hidden" id="hdnViewPatientMenuText" value="@Constants.ViewEditPatientDetails" />
</body>

</html>