SCA.Indigo.Web.UI/Controllers/UserAdminController.cs
// ***********************************************************************
// Assembly         : SCA.Indigo.Web.UI.Controllers
// Author           : sphapale / bsahoo
// Created          : 09-03-2015
//
// Last Modified By : Basanta
// Last Modified On : 13- Mar-2015
// ***********************************************************************
// <copyright file="UserAdminController.cs" company="Capgemini">
//     Capgemini. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace SCA.Indigo.Web.UI.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;
    using SCA.Indigo.Business.BusinessModels;
    using SCA.Indigo.Common;
    using SCA.Indigo.Web.UI.Helper;
    using SCA.Indigo.Web.UI.ViewModel.UserAdmin;

    /// <summary>
    /// User Admin Controller
    /// </summary>
    [Authorize]
    public class UserAdminController : Controller
    {
        #region Map Role To User Functionality

        #region Constants

        /// <summary>
        /// User Id
        /// </summary>
        private string userId = ControllerHelper.CurrentUser.UserId.ToString();

        /// <summary>
        /// User Admin Helper
        /// </summary>
        UserAdminHelper userAdminHelper = new UserAdminHelper();

        #endregion

        /// <summary>
        /// Get Map User Roles
        /// </summary>
        /// <returns>
        /// return action result
        /// </returns>
        public ActionResult MapUserRoles()
        {            
            UserAdminViewModel userAdminViewModel = this.userAdminHelper.GetMapUserRoles();
            return this.View(Constants.ViewMapUserRoles, userAdminViewModel);
        }

        /// <summary>
        /// Get Role To Functionality Details
        /// </summary>
        /// <param name="roleId">The role identifier.</param>
        /// <returns>
        /// return action result
        /// </returns>
        [HttpGet]
        public ActionResult GetRoleToFunctionality(string roleId)
        {
            List<UserMenuDetailsBusinessModel> rolesToFunctionalityMapping = this.userAdminHelper.GetRolesToFunctionality(roleId);
            return this.Json(rolesToFunctionalityMapping, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Save Role To Functionality
        /// </summary>
        /// <param name="roleMenuMappingList">The role menu mapping list.</param>
        /// <param name="roleId">The role identifier.</param>
        /// <returns>
        /// return action result
        /// </returns>
        [HttpPost]
        public ActionResult SaveRoleToFunctionality(List<UserMenuDetailsBusinessModel> roleMenuMappingList, string roleId)
        {
            int saveResponse = this.userAdminHelper.SaveRolesToFunctionality(roleMenuMappingList, roleId);
            LogHelper.LogAction(Constants.ActionNameSaveUserCustomerMapping, Constants.UserAdminController, Constants.ActionNameSaveUserCustomerMapping, this.userId);
            return this.Json(saveResponse, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Get Role To User
        /// </summary>
        /// <param name="userName">Name of the user.</param>
        /// <param name="roleId">The role identifier.</param>
        /// <param name="sapCustomerId">The sap customer identifier.</param>
        /// <returns>
        /// return action result
        /// </returns>
        [HttpGet]
        public ActionResult GetRoleToUser(string userName, string roleId, string sapCustomerId)
        {
            List<UserMenuDetailsBusinessModel> roleToUserMapping = this.userAdminHelper.GetRoleToUser(userName, roleId, sapCustomerId);
            return this.Json(roleToUserMapping, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Save Role To User
        /// </summary>
        /// <param name="userRoleMappingList">The user role mapping list.</param>
        /// <param name="roleId">The role identifier.</param>
        /// <returns>
        /// return action result
        /// </returns>
        [HttpPost]
        public ActionResult SaveRoleToUser(List<UserMenuDetailsBusinessModel> userRoleMappingList, string roleId)
        {
            int saveRoleToUserResponse = this.userAdminHelper.SaveRoleToUser(userRoleMappingList, roleId);
            LogHelper.LogAction(Constants.ActionNameSaveUserCustomerMapping, Constants.UserAdminController, Constants.ActionNameSaveUserCustomerMapping, this.userId);
            return this.Json(saveRoleToUserResponse, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Save New Role
        /// </summary>
        /// <param name="roleName">Name of the role.</param>
        /// <param name="isSCA">if set to <c>true</c> [is sca].</param>
        /// <returns>
        /// return action result
        /// </returns>
        [HttpPost]
        public ActionResult SaveNewRole(string roleName, bool isSCA)
        {
            int saveNewRoleResponse = this.userAdminHelper.SaveNewRole(roleName, isSCA);
            LogHelper.LogAction(Constants.ActionNameSaveUserCustomerMapping, Constants.UserAdminController, Constants.ActionNameSaveUserCustomerMapping, this.userId);
            return this.Json(saveNewRoleResponse, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Map User to Customer functionality

        /// <summary>
        /// This will return view
        /// </summary>
        /// <returns>
        /// all users
        /// </returns>
        public ActionResult MapUserCustomer()
        {            
            UserAdminViewModel mapUserCustomerViewModel = new UserAdminViewModel();
            mapUserCustomerViewModel = this.userAdminHelper.GetUserCustomerMapping();
            return this.View(Constants.ViewMapUserCustomer, mapUserCustomerViewModel);
        }

        /// <summary>
        /// This will user to get customers when dropdown gets selected.
        /// </summary>
        /// <param name="userID">The user identifier.</param>
        /// <param name="isFirstTime">if set to <c>true</c> [is first time].</param>
        /// <returns>
        /// Customers for User
        /// </returns>
        [HttpGet]        
        public ActionResult GetUserToAllCustomer(string userID, bool isFirstTime)
        {
            UserAdminViewModel objUserAdminViewModel = this.userAdminHelper.GetUserToAllCustomer(userID, isFirstTime);
            return this.Json(objUserAdminViewModel, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Save User customer User mapping
        /// </summary>
        /// <param name="objCustomerList">The object customer list.</param>
        /// <param name="objUserId">The object user identifier.</param>
        /// <returns>
        /// response data
        /// </returns>
        [HttpPost]
        public ActionResult SaveUserToCustomers(List<UsersBusinessModel> objCustomerList, string objUserId)
        {
            int saveUserToCustomerResponse = this.userAdminHelper.SaveUserToCustomer(objCustomerList, objUserId);
            LogHelper.LogAction(Constants.ActionNameSaveUserCustomerMapping, Constants.UserAdminController, Constants.ActionNameSaveUserCustomerMapping, this.userId);
            return this.Json(saveUserToCustomerResponse, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Carehome Users
        /// <summary>
        /// Load User Carehome Screen
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult MapUserToCareHome()
        {
            CareHomeUserViewModel careHomeUserViewModel = new CareHomeUserViewModel();
            careHomeUserViewModel.UserId = this.userId;
            careHomeUserViewModel.Customers = GenericHelper.GetCustomersListForDropdown(careHomeUserViewModel.UserId);

            return View(Constants.ViewMapUserCareHome, careHomeUserViewModel);
        }

        /// <summary>
        /// Gets Carehome or Users Details for DropDown
        /// </summary>
        /// <param name="typeId">1 For Carehome & 2 for Users Details</param>
        /// <param name="valueId">Gets Customer Id</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetDDLForCareHomeUser(string typeId, string valueId)
        {
            SelectList ddlList = null;
            var strtypeId = "1";

            if (typeId == strtypeId)
                ddlList = GenericHelper.GetCareHomeOnCustomerId(valueId, userId);
            else
                ddlList= GenericHelper.GetCareHomeUsers(valueId, userId);

            return this.Json(ddlList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Saves Mapped Users to Carehome 
        /// </summary>
        /// <param name="objUserCarehomeBusinessModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SaveCareHomeUsers(UserCareHomeBusinessModel objUserCareHomeBusinessModel)
        {
            int response = userAdminHelper.SaveCareHomeUsers(objUserCareHomeBusinessModel);
            return this.Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

SCA.Indigo.Web.UI/Views/UserAdmin/MapUserCareHome.cshtml
@using SCA.Indigo.Web.UI.Resource
@using SCA.Indigo.Web.UI.Helper
@using SCA.Indigo.Common.Enums
@model SCA.Indigo.Web.UI.ViewModel.UserAdmin.CareHomeUserViewModel

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    @Styles.Render("~/Content/MapUserToCareHome")
    @Scripts.Render("~/bundles/MapUserToCareHome")
    <script type="text/javascript">
        $jqGrid = jQuery.noConflict();
        $jqGrid(document).ready(function () {
            $jqGrid("#ddlCarehome").multiselect("disable");
            $jqGrid("#ddlUsers").multiselect("disable");
            $jqGrid("#ddlCustomer").select2();
        });

    </script>

</head>
<body>
    <form id="frm_MapUserCarehome">
       
        <span class="page_heading">@Common.resHdrCarehomeUsers</span>


        <ul class="care_home_maintenance_ul">
            <li class="width_910">
                <div class="map_rols_user_cell new_select_for_search margin_bot_12">
                    <span class="care_home_maintenance_lable">@Common.resCarehomeUserslblCustomerName</span>
                    <span class="care_home_maintenance_select select-style width_787" tabindex="1">
                        @Html.DropDownList("ddlCustomer", (IEnumerable<SelectListItem>)Model.Customers, @Common.resCarehomeUserddlCustomer, new { @class = "custom-select width_787", @id = "ddlCustomer", tabindex = "1" })
                    </span>
                </div>
            </li>
        </ul>
        <ul class="care_home_maintenance_ul">
            <li class="width_540">
                <div class="map_rols_user_cell new_select_for_search margin_bot_12">
                    <span class="care_home_maintenance_lable">@Common.resCarehomeUserslblCarehomeName</span>
                    <span class="care_home_maintenance_select select-style width_418 miltiselect_500" tabindex="1">
                        @Html.DropDownList("ddlCarehome", Enumerable.Empty<SelectListItem>(), new { multiple = "multiple", @class = "custom-select width_550", @id = "ddlCarehome", tabindex = "2" })
                    </span>
                </div>
            </li>

            <li class="width_auto margin_right_0">
                <div class="map_rols_user_cell new_select_for_search margin_bot_12">
                    <span class="care_home_maintenance_lable width_108">@Common.resCarehomeUserslblCarehomeUser</span>
                    <span class="care_home_maintenance_input select-style width_235">
                        @Html.DropDownList("ddlUsers", Enumerable.Empty<SelectListItem>(), new { multiple = "multiple", @class = "custom-select", @id = "ddlUsers", tabindex = "3" })
                    </span>
                </div>
            </li>
        </ul>
 
      
        <div class="search_form_main_btns padding_0">
            <input type="button" value="@Common.resCarehomeUserbtnSubmit" class="search_form_buttons padding_left_right_20 btnAddProduct" id="btnSubmit" />
            <input type="button" value="@Common.resCarehomeUserbtnUndo" class="search_form_buttons padding_left_right_20 btnAddProduct" id="btnUndo" />
        </div>

        <div class="j_lightbox_error" id="j_lightbox_error">
            <div class="j_lightbox_error_wrapper">
                <div class="pop_error">
                    <div id="divMapUserCarehomeErrorMessage" class="pop_error">
                    </div>
                    <br />
                    <div class="j_lightbox_btns search_form_main_btns">
                        <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15 j_lightbox_error_ok">@Common.resbtnErrorOk</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="divSaveCarehomeUsers" style="display:none" class="validation_msg">
            <label class="success_msg">@Common.resCarehomeUserConfirmMsg</label>
        </div>
        <div id="divSaveCarehomeUsersSuccess" style="display:none" class="validation_msg">
            <label class="success_msg">@Common.resCarehomeUserSuccessMsg</label>
        </div>
        <input type="hidden" id="hdnresDefaultddlCarehome" value="@Common.resCarehomeUserddlCarehome" />
        <input type="hidden" id="hdnresDefaultddlUser" value="@Common.resCarehomeUserddlUser" />

        <input type="hidden" id="hdnresCustomerValidationMsg" value="@Common.resCustomerValidationMsg" />
        <input type="hidden" id="hdnresCarehomeValidationMsg" value="@Common.resCarehomeValidationMsg" />
        <input type="hidden" id="hdnresUserValidationMsg" value="@Common.resUserValidationMsg" />
    </form>
    <script type="text/javascript" src="~/Scripts/jquery.multiselect.filter.min.js"></script>
    <script type="text/javascript">
        $jqGrid = jQuery.noConflict();
        $jqGrid(document).ready(function () {
            $jqComm("#ddlCarehome").multiselect().multiselectfilter();
            $jqComm("#ddlUsers").multiselect().multiselectfilter();
            //$jqComm("#ddlCustomer").multiselectfilter();
        });
    </script>
    @Html.Hidden("hdnLoadDDLAction", Url.Action("GetDDLForCareHomeUser", "UserAdmin"), new { id = "hdnLoadDDLAction" })
    @Html.Hidden("hdnSubmitAction", Url.Action("SaveCareHomeUsers", "UserAdmin"), new { id = "hdnSubmitAction" })
</body>
</html>


SCA.Indigo.Web.UI/Views/UserAdmin/MapUserCustomer.cshtml
@model SCA.Indigo.Web.UI.ViewModel.UserAdmin.UserAdminViewModel
@using SCA.Indigo.Web.UI.Resource
@using SCA.Indigo.Web.UI.Resource
@using System.Configuration;
@using SCA.Indigo.Web.UI.Helper
@using SCA.Indigo.Common.Enums

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <script type="text/javascript">
        $jqGrid = jQuery.noConflict();
        $jqGrid(document).ready(function () {

            $jqGrid("#jqMapUserCustomer").jqGrid({
                datatype: "local",
                colNames: ['@Common.resSrNo', '@Common.resGrdCustomerId', '@Common.resSAPCustomerNumber', '@Common.reslblCustomer', '@Common.resMap'],
                colModel: [
                    { name: 'SrNo', index: 'SrNo', editable: false, width: '70px', classes: 'align_center' },
                    { name: 'CustomerId', index: 'CustomerId', hidden: true, editable: false, width: '185px', classes: 'align_left padding_left_10' },
                    { name: 'SAPCustomerNumber', index: 'SAPCustomerNumber', editable: false, width: '170px', classes: 'align_center' },
                    { name: 'CustomerName', index: 'CustomerName', editable: false, width: '526px', classes: 'align_left padding_left_10' },
                    { name: 'MapCustomer', index: 'MapCustomer', edittype: 'checkbox', width: '110', classes: 'align_center', formatter: FormatMapCustomer, editoptions: { value: 'True:False' }, formatoptions: { disabled: false }, sortable: false },
                ],
                height: '150',
                width: 'auto',
                toppager: false,
                jsonReader: { repeatitems: false },
                pager: $jqGrid("#jqMapUserCustomerTablePager"),
                rowNum: 300,
                rowList: [300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200],
                viewrecords: true,
                autowidth: false,
                sortname: "",
                sortorder: "asc",
                gridComplete: function () {
                    $jqGrid('#jqMapUserCustomer_left').hide();
                    $jqGrid('#jqMapUserCustomerTablePager_left').hide();
                    $jqGrid('.ui-paging-info').css("text-align", "left");
                    var rowcount = $jqGrid(this).jqGrid('getGridParam', 'records');
                    if (rowcount == 0) {
                        $jqGrid('#jqMapUserCustomerTablePager_center').hide();
                    }
                    else {
                        $jqGrid('#jqMapUserCustomerTablePager_center').show();
                    }
                    $jqGrid('.ui-pg-input').bind('keyup', function (e) {
                        var val = $jqGrid(this).val().trim();
                        ValidationGridPageInput(e, val);
                    });
                },
                onCellSelect: function (rowid, iCol) {
                    $jqGrid(this).jqGrid('editRow', rowid, true);
                },
                ondblClickRow: function (rowid) {
                },
                loadComplete: function (data) {
                    $jqComm('#jqMapUserCustomer input[type="checkbox"]').ezMark();
                },

            }).navGrid("#jqMapUserCustomerTablePager",
            { search: false, refresh: false, add: false, edit: false, del: false },
            {},
            {},
            {}
        );

            $jqGrid("#jqMapUserCustomer").trigger("reloadGrid");
            $jqGrid("#jqgh_jqMapUserCustomer_Remove").removeClass("ui-jqgrid-sortable");

            $jqGrid('#chkMapCustomer').click(function (event) {
                if ($jqGrid("#chkMapCustomer").is(":checked")) {
                    $jqGrid(".chkMapCustomerClass").prop("checked", true);
                } else {
                    $jqGrid(".chkMapCustomerClass").prop("checked", false);
                }
            });

            // Load all customers for the first time                        
            LoadUserToCustomer(true);

            // Check for ViewOnly 
            //linkId: - Menu Link Id, element: - Main Div of the Form
            CommonScriptObj.DisableFormControls("frm_MapUserCustomer");

            // Clear Patient Sesion
            CommonScriptObj.ClearPatientSession();

        });//end of ready
    </script>

    <style>

        .search_cell {
            padding: 6px 10px;
        }

        .page_heading {
            padding-top: 5px;
        }
    </style>

</head>
<body>
    <form id="frm_MapUserCustomer">
        <span class="page_heading">@Common.resMapCustomerToUser</span>

        <div class="map_rols_user_cell new_select_for_search">
            <span class="map_rols_user_input select-style">
                @Html.DropDownList("ddlUserToCustomer", (IEnumerable<SelectListItem>)Model.UserToCustomerItems, @Common.resUserDropdown, new { @class = "custom-select", @onchange = "LoadUserToCustomer(false);" })
            </span>
        </div>


        <div class="table_section_2 mCustomScrollbar">
            <table id="jqMapUserCustomer" class="analysis_information_table"></table>
            <div id="jqMapUserCustomerTablePager"></div>
        </div>

        <div class="form_main_btns">
            <a href="javascript:void(0);" class="search_form_buttons padding_left_right_20" tabindex="12" onclick="SaveMapUserToCustomer(this);" id="btnSaveUserCustomer">@Common.resBtnGeneralSubmit</a>&nbsp;&nbsp;
            <a href="javascript:void(0);" tabindex="13" class="search_form_buttons padding_left_right_20" id="btnResetUserCustomer" onclick="ResetAll();">@Common.resBtnGeneralReset</a>
        </div>

        <div class="j_lightbox_error" id="j_lightbox_error">
            <div class="j_lightbox_error_wrapper">
                <div class="pop_error">
                    <div id="divErrorMessage" class="pop_error">
                    </div>
                    <br />
                    <div class="j_lightbox_btns search_form_main_btns">
                        <a href="javascript:void(0);" class="search_form_buttons padding_left_right_15 j_lightbox_error_ok small_btn_2">@Common.resbtnErrorOk</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="divNoCustomerFound" style="display:none;min-height: 19px;"></div>
        <div id="divOutPutMessage" style="display:none;min-height: 19px;">

        </div>

        <div id="divErrorMessage" style="display:none;min-height: 19px;">@Common.resGenericErrorForWrong</div>
        <div id="divNoDatabaseChange" style="display:none;min-height: 19px;">@Common.resNoDatabaseChange</div>
        <div id="divNotAlreadyMapped" style="display:none;min-height: 19px;">@Common.resNotAlreadyMapped</div>
        <input type="hidden" id="hdnerrorUserToCustomer" value="@Common.resErrorUserToCustomer" />
        <input type="hidden" id="hdnErrorInvaliSelection" value="@Common.resErrorInvaliSelection" />
        <input type="hidden" id="hdnresOutPutMessage" value="@Common.resOutPutMessage" />
        <input type="hidden" id="hdnUserAdminResetMessage" value="@Common.resUserAdminResetMessage" />
        <input type="hidden" id="hdnAdminUserName" value="@Constants.AdminUser"/>
        @Scripts.Render("~/bundles/UserAdmin")
    </form>
</body>

</html>